version: "3"

services:
  api:
    command: yarn start
    build: .
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/uri
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - api

#   smtp4dev:
#     image: rnwood/smtp4dev:v3
#     restart: always
#     ports:
#       - '5000:5000'
#       - '25:25'
#       - '143:143'
#     volumes:
#       - smtp4dev-data:/smtp4dev
#     environment:
#       - ServerOptions__HostName=${EMAIL_HOST}
#       - RelayOptions__Login=${EMAIL_USERNAME}
#       - RelayOptions__Password=${EMAIL_PASSWORD}

# volumes:
#   smtp4dev-data:
