@startuml
title User flow


partition HomePage {
  (*) --> "Register" 
  note right: Must have valid invitation
  --> "Login"
 
  partition AddClaim {
    --> "Add new article"
    --> "Add claim" as addClaim
    if "Add more" then 
      -->[Yes] addClaim
    else
      -->[No] (*)
    endif
    --> "a"
  }
}



--> (*)

@enduml
