@startuml Architecure overview

package "User" {
  [FrontEnd web app] as fe
}

package "Backend deployment" {

  cloud {
    [APP services with LoadBalancer] as be
  }

  cloud {
    [WebScrapping Flask service] as scrapping_se
  }

  database "MongoDB Cluster" {
    [Mongo] as mongo
  }

  component "Papertrail \nLog analysis" as log

  ' component "ElasticSearch in future\nfor efficient text searches" as elastic
  ' component "Redis in future\n for session management" as redis
}


[fe] --> [be]
[fe] --> [scrapping_se]
[be] --> [mongo]
[be] --> [log]
[scrapping_se] --> [log]
' [be] --> [elastic]
@enduml