name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  NODE_ENV: test
  PORT: 3000
  JWT_SECRET: bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
  JWT_EXPIRATION_MINUTES: 15
  MONGO_URI: mongodb://localhost/express-rest-es2017-boilerplate
  MONGO_URI_TESTS: mongodb://localhost/express-rest-es2017-boilerplate
  EMAIL_PORT: 587
  EMAIL_HOST: smtp-relay.sendinblue.com
  EMAIL_USERNAME: smtp-username
  EMAIL_PASSWORD: smtp-password


jobs:
  test_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        mongodb-version: ['6.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install yarn -g

      - name: Build App
        run: yarn
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 27017


      - run: yarn validate
        env:
          CI: true
          
      - run: yarn coverage

