name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        mongodb-version: ['6.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install yarn -g

      - name: Build App
        run: yarn
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          
      - name: create env file
        run: |
          touch .env
          echo NODE_ENV=test >> .env
          echo PORT=3000 >> .env
          echo JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4 >> .env
          echo JWT_EXPIRATION_MINUTES=15 >> .env
          echo MONGO_URI=mongodb://localhost/express-rest-es2017-boilerplate >> .env
          echo MONGO_URI_TESTS=mongodb://localhost/express-rest-es2017-boilerplate >> .env
          echo EMAIL_PORT=587 >> .env
          echo EMAIL_HOST=smtp-relay.sendinblue.com >> .env
          echo EMAIL_USERNAME=smtp-username >> .env
          echo EMAIL_USERNAME=smtp-password >> .env

      - run: yarn validate
        env:
          CI: true
          
      - run: yarn coverage

